/**
 * SUMMONER ACTION TYPES
 */
export const SEARCH_SUMMONER = "SEARCH_SUMMONER";
export const SEARCH_SUMMONER_SUCCESS = "SEARCH_SUMMONER_SUCCESS";
export const SEARCH_SUMMONER_ERROR = "SEARCH_SUMMONER_ERROR";
export const CREATE_SUMMONER = "CREATE_SUMMONER";
export const CREATE_SUMMONER_SUCCESS = "CREATE_SUMMONER_SUCCESS";
export const CREATE_SUMMONER_ERROR = "CREATE_SUMMONER_ERROR";
export const UPDATE_SUMMONER = "UPDATE_SUMMONER";
export const UPDATE_SUMMONER_SUCCESS = "UPDATE_SUMMONER_SUCCESS";
export const UPDATE_SUMMONER_ERROR = "UPDATE_SUMMONER_ERROR";

/**
 * ALERT ACTION TYPES
 */
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

/**
 * LEADEREBOARD ACTION TYPES
 */
export const LOAD_LEADERBOARD = "LOAD_LEADERBOARD";
export const LOAD_LEADERBOARD_SUCCESS = "LOAD_LEADERBOARD_SUCCESS";
export const LOAD_LEADERBOARD_ERROR = "LOAD_LEADERBOARD_ERROR";

/**
 * REGION ACTION TYPES
 */
export const LOAD_REGION_SUCCESS = "LOAD_REGION_SUCCESS";
export const LOAD_REGION_ERROR = "LOAD_REGION_ERROR";
export const SWITCH_REGION_SUCCESS = "SWITCH_REGION_SUCCESS";
export const SWITCH_REGION_ERROR = "SWITCH_REGION_ERROR";
export const USING_REGION = "USING_REGION";
export const NOT_USING_REGION = "NOT_USING_REGION";

/**
 * LEAGUE ACTION TYPES
 */
export const SWITCH_LEAGUE_SUCCESS = "SWITCH_LEAGUE_SUCCESS";
export const SWITCH_LEAGUE_ERROR = "SWITCH_LEAGUE_ERROR";
