export const SEARCH_SUMMONER = "SEARCH_SUMMONER";
export const SEARCH_SUMMONER_SUCCESS = "SEARCH_SUMMONER_SUCCESS";
export const SEARCH_SUMMONER_ERROR = "SEARCH_SUMMONER_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOAD_LEADERBOARD = "LOAD_LEADERBOARD";
export const LOAD_LEADERBOARD_SUCCESS = "LOAD_LEADERBOARD_SUCCESS";
export const LOAD_LEADERBOARD_ERROR = "LOAD_LEADERBOARD_ERROR";

export const LOAD_REGION_SUCCESS = "LOAD_REGION_SUCCESS";
export const LOAD_REGION_ERROR = "LOAD_REGION_ERROR";
export const SWITCH_REGION_SUCCESS = "SWITCH_REGION_SUCCESS";
export const SWITCH_REGION_ERROR = "SWITCH_REGION_ERROR";

export const SWITCH_LEAGUE_SUCCESS = "SWITCH_LEAGUE_SUCCESS";
export const SWITCH_LEAGUE_ERROR = "SWITCH_LEAGUE_ERROR";
