export const SEARCH_SUMMONER = "SEARCH_SUMMONER";
export const SEARCH_SUMMONER_SUCCESS = "SEARCH_SUMMONER_SUCCESS";
export const SEARCH_SUMMONER_ERROR = "SEARCH_SUMMONER_ERROR";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const LOAD_LEADERBOARD = "LOAD_LEADERBOARD";
export const LOAD_LEADERBOARD_SUCCESS = "LOAD_LEADERBOARD_SUCCESS";
export const LOAD_LEADERBOARD_ERROR = "LOAD_LEADERBOARD_ERROR";
